// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-QMIGNCH
// DateTime: 24.05.2021 19:09:15
// UserName: Алексей
// Input file <./Land.y - 24.05.2021 19:09:14>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using System.Linq;
using Land.Core;

namespace Land.Core.Specification.Parsing
{
public enum Tokens {error=2,EOF=3,OR=4,ARGS_LROUND_BRACKET=5,LROUND_BRACKET=6,
    RROUND_BRACKET=7,LCURVE_BRACKET=8,RCURVE_BRACKET=9,COLON=10,COMMA=11,PROC=12,
    EQUALS=13,MINUS=14,PLUS=15,EXCLAMATION=16,DOT=17,ARROW=18,
    LEFT=19,RIGHT=20,LINESTART=21,REGEX=22,NAMED=23,STRING=24,
    ID=25,ENTITY_NAME=26,OPTION_NAME=27,CATEGORY_NAME=28,POSITION=29,RNUM=30,
    OPTIONAL=31,ZERO_OR_MORE=32,ONE_OR_MORE=33,IS_LIST_NODE=34,PREC_NONEMPTY=35};

public struct ValueType
{ 
	public int intVal; 
	public double doubleVal;
	public Quantifier quantVal;
	public bool boolVal;
	public string strVal;
	public Entry entryVal;
	public Alternative altVal;
	public ArgumentGroup argGroupVal;
	public dynamic dynamicVal;
	public OptionDeclaration optDeclVal;
	
	public List<dynamic> dynamicList;
	public List<OptionDeclaration> optionsList;
	public List<string> strList;	
	public List<Alternative> altList;
	
	public HashSet<string> strSet;
	
	public Dictionary<string, Dictionary<string, List<dynamic>>> optionGroupsDict; 
	public Dictionary<string, List<dynamic>> optionsDict;
	public Tuple<string, List<dynamic>> optionTuple;
	
	// Информация о количестве повторений
	public Nullable<Quantifier> optQuantVal;
	public Nullable<double> optDoubleVal;
}
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,Land.Core.SegmentLocation> {
  private Land.Core.SegmentLocation __yylloc = new Land.Core.SegmentLocation();
  public override Land.Core.SegmentLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public Land.Core.SegmentLocation yylloc;
  public ScanObj( int t, ValueType val, Land.Core.SegmentLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, Land.Core.SegmentLocation>
{
  // Verbatim content from ./Land.y - 24.05.2021 19:09:14
    public Parser(AbstractScanner<ValueType, SegmentLocation> scanner) : base(scanner) { }
    
    public Grammar ConstructedGrammar;
    public List<Message> Log = new List<Message>();
    
    private HashSet<string> Aliases = new HashSet<string>();
  // End verbatim content from ./Land.y - 24.05.2021 19:09:14

#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[66];
  private static State[] states = new State[97];
  private static string[] nonTerms = new string[] {
      "lp_description", "quantifier", "entry_core", "group", "optional_alias", 
      "grammar_entity", "entry", "grammar_entities_list", "body", "prec_nonempty", 
      "opt_linestart", "argument_group", "argument", "alternative", "option", 
      "opt_args", "args", "context_opt_args", "entry_args", "context_option_groups", 
      "context_options", "option_or_block", "options", "context_option", "pair_border_group_content", 
      "pair_border", "$accept", "structure", "options_section", "element", "terminal", 
      "nonterminal", "pair", "category_block", };

  static Parser() {
    states[0] = new State(new int[]{26,37},new int[]{-1,1,-28,3,-30,96,-31,36,-32,94,-33,95});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{12,4,26,37},new int[]{-30,35,-31,36,-32,94,-33,95});
    states[4] = new State(new int[]{28,8,3,-44},new int[]{-29,5,-34,6});
    states[5] = new State(-2);
    states[6] = new State(new int[]{28,8,3,-44},new int[]{-29,7,-34,6});
    states[7] = new State(-45);
    states[8] = new State(new int[]{27,11,8,31},new int[]{-22,9,-15,10});
    states[9] = new State(-46);
    states[10] = new State(-47);
    states[11] = new State(new int[]{6,17,25,-53,22,-53,28,-53,3,-53,9,-53,27,-53},new int[]{-16,12});
    states[12] = new State(-63,new int[]{-8,13});
    states[13] = new State(new int[]{25,15,22,16,28,-51,3,-51,9,-51,27,-51},new int[]{-6,14});
    states[14] = new State(-62);
    states[15] = new State(-64);
    states[16] = new State(-65);
    states[17] = new State(new int[]{30,22,22,23,24,24,25,25},new int[]{-17,18,-13,29,-12,30});
    states[18] = new State(new int[]{7,19,11,20});
    states[19] = new State(-52);
    states[20] = new State(new int[]{30,22,22,23,24,24,25,25},new int[]{-13,21,-12,30});
    states[21] = new State(-54);
    states[22] = new State(-56);
    states[23] = new State(-57);
    states[24] = new State(-58);
    states[25] = new State(new int[]{5,26,7,-59,11,-59});
    states[26] = new State(new int[]{30,22,22,23,24,24,25,25},new int[]{-17,27,-13,29,-12,30});
    states[27] = new State(new int[]{7,28,11,20});
    states[28] = new State(-61);
    states[29] = new State(-55);
    states[30] = new State(-60);
    states[31] = new State(-49,new int[]{-23,32});
    states[32] = new State(new int[]{9,33,27,11},new int[]{-15,34});
    states[33] = new State(-48);
    states[34] = new State(-50);
    states[35] = new State(-3);
    states[36] = new State(-5);
    states[37] = new State(new int[]{10,38,13,54});
    states[38] = new State(new int[]{19,41,21,53,22,-10},new int[]{-11,39});
    states[39] = new State(new int[]{22,40});
    states[40] = new State(-8);
    states[41] = new State(new int[]{25,45,22,46,6,47},new int[]{-26,42});
    states[42] = new State(new int[]{20,43});
    states[43] = new State(new int[]{25,45,22,46,6,47},new int[]{-26,44});
    states[44] = new State(-11);
    states[45] = new State(-12);
    states[46] = new State(-13);
    states[47] = new State(new int[]{25,45,22,46,6,47},new int[]{-25,48,-26,52});
    states[48] = new State(new int[]{7,49,4,50});
    states[49] = new State(-14);
    states[50] = new State(new int[]{25,45,22,46,6,47},new int[]{-26,51});
    states[51] = new State(-16);
    states[52] = new State(-15);
    states[53] = new State(-9);
    states[54] = new State(-21,new int[]{-9,55,-14,92});
    states[55] = new State(new int[]{4,56,12,-17,26,-17});
    states[56] = new State(-21,new int[]{-14,57});
    states[57] = new State(new int[]{18,60,4,-23,12,-23,26,-23,7,-23,28,-28,22,-28,25,-28,6,-28},new int[]{-5,58,-7,59,-20,62});
    states[58] = new State(-18);
    states[59] = new State(-20);
    states[60] = new State(new int[]{25,61});
    states[61] = new State(-22);
    states[62] = new State(new int[]{28,74,22,86,25,87,6,89},new int[]{-3,63,-4,88});
    states[63] = new State(new int[]{5,71,31,-26,32,-26,33,-26,35,-26,18,-26,28,-26,22,-26,25,-26,6,-26,4,-26,12,-26,26,-26,7,-26},new int[]{-19,64});
    states[64] = new State(new int[]{31,68,32,69,33,70,35,-39,18,-39,28,-39,22,-39,25,-39,6,-39,4,-39,12,-39,26,-39,7,-39},new int[]{-2,65});
    states[65] = new State(new int[]{35,67,18,-35,28,-35,22,-35,25,-35,6,-35,4,-35,12,-35,26,-35,7,-35},new int[]{-10,66});
    states[66] = new State(-24);
    states[67] = new State(-34);
    states[68] = new State(-36);
    states[69] = new State(-37);
    states[70] = new State(-38);
    states[71] = new State(new int[]{30,22,22,23,24,24,25,25},new int[]{-17,72,-13,29,-12,30});
    states[72] = new State(new int[]{7,73,11,20});
    states[73] = new State(-25);
    states[74] = new State(new int[]{5,75});
    states[75] = new State(new int[]{25,80},new int[]{-21,76,-24,85});
    states[76] = new State(new int[]{7,77,11,78});
    states[77] = new State(-27);
    states[78] = new State(new int[]{25,80},new int[]{-24,79});
    states[79] = new State(-29);
    states[80] = new State(new int[]{5,82,7,-33,11,-33},new int[]{-18,81});
    states[81] = new State(-31);
    states[82] = new State(new int[]{30,22,22,23,24,24,25,25},new int[]{-17,83,-13,29,-12,30});
    states[83] = new State(new int[]{7,84,11,20});
    states[84] = new State(-32);
    states[85] = new State(-30);
    states[86] = new State(-40);
    states[87] = new State(-41);
    states[88] = new State(-42);
    states[89] = new State(-21,new int[]{-9,90,-14,92});
    states[90] = new State(new int[]{7,91,4,56});
    states[91] = new State(-43);
    states[92] = new State(new int[]{18,60,4,-23,12,-23,26,-23,7,-23,28,-28,22,-28,25,-28,6,-28},new int[]{-5,93,-7,59,-20,62});
    states[93] = new State(-19);
    states[94] = new State(-6);
    states[95] = new State(-7);
    states[96] = new State(-4);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-27, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-28,12,-29});
    rules[3] = new Rule(-28, new int[]{-28,-30});
    rules[4] = new Rule(-28, new int[]{-30});
    rules[5] = new Rule(-30, new int[]{-31});
    rules[6] = new Rule(-30, new int[]{-32});
    rules[7] = new Rule(-30, new int[]{-33});
    rules[8] = new Rule(-31, new int[]{26,10,-11,22});
    rules[9] = new Rule(-11, new int[]{21});
    rules[10] = new Rule(-11, new int[]{});
    rules[11] = new Rule(-33, new int[]{26,10,19,-26,20,-26});
    rules[12] = new Rule(-26, new int[]{25});
    rules[13] = new Rule(-26, new int[]{22});
    rules[14] = new Rule(-26, new int[]{6,-25,7});
    rules[15] = new Rule(-25, new int[]{-26});
    rules[16] = new Rule(-25, new int[]{-25,4,-26});
    rules[17] = new Rule(-32, new int[]{26,13,-9});
    rules[18] = new Rule(-9, new int[]{-9,4,-14,-5});
    rules[19] = new Rule(-9, new int[]{-14,-5});
    rules[20] = new Rule(-14, new int[]{-14,-7});
    rules[21] = new Rule(-14, new int[]{});
    rules[22] = new Rule(-5, new int[]{18,25});
    rules[23] = new Rule(-5, new int[]{});
    rules[24] = new Rule(-7, new int[]{-20,-3,-19,-2,-10});
    rules[25] = new Rule(-19, new int[]{5,-17,7});
    rules[26] = new Rule(-19, new int[]{});
    rules[27] = new Rule(-20, new int[]{-20,28,5,-21,7});
    rules[28] = new Rule(-20, new int[]{});
    rules[29] = new Rule(-21, new int[]{-21,11,-24});
    rules[30] = new Rule(-21, new int[]{-24});
    rules[31] = new Rule(-24, new int[]{25,-18});
    rules[32] = new Rule(-18, new int[]{5,-17,7});
    rules[33] = new Rule(-18, new int[]{});
    rules[34] = new Rule(-10, new int[]{35});
    rules[35] = new Rule(-10, new int[]{});
    rules[36] = new Rule(-2, new int[]{31});
    rules[37] = new Rule(-2, new int[]{32});
    rules[38] = new Rule(-2, new int[]{33});
    rules[39] = new Rule(-2, new int[]{});
    rules[40] = new Rule(-3, new int[]{22});
    rules[41] = new Rule(-3, new int[]{25});
    rules[42] = new Rule(-3, new int[]{-4});
    rules[43] = new Rule(-4, new int[]{6,-9,7});
    rules[44] = new Rule(-29, new int[]{});
    rules[45] = new Rule(-29, new int[]{-34,-29});
    rules[46] = new Rule(-34, new int[]{28,-22});
    rules[47] = new Rule(-22, new int[]{-15});
    rules[48] = new Rule(-22, new int[]{8,-23,9});
    rules[49] = new Rule(-23, new int[]{});
    rules[50] = new Rule(-23, new int[]{-23,-15});
    rules[51] = new Rule(-15, new int[]{27,-16,-8});
    rules[52] = new Rule(-16, new int[]{6,-17,7});
    rules[53] = new Rule(-16, new int[]{});
    rules[54] = new Rule(-17, new int[]{-17,11,-13});
    rules[55] = new Rule(-17, new int[]{-13});
    rules[56] = new Rule(-13, new int[]{30});
    rules[57] = new Rule(-13, new int[]{22});
    rules[58] = new Rule(-13, new int[]{24});
    rules[59] = new Rule(-13, new int[]{25});
    rules[60] = new Rule(-13, new int[]{-12});
    rules[61] = new Rule(-12, new int[]{25,5,-17,7});
    rules[62] = new Rule(-8, new int[]{-8,-6});
    rules[63] = new Rule(-8, new int[]{});
    rules[64] = new Rule(-6, new int[]{25});
    rules[65] = new Rule(-6, new int[]{22});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // lp_description -> structure, PROC, options_section
{ 
			ConstructedGrammar.PostProcessing();
			Log.AddRange(ConstructedGrammar.CheckValidity()); 
		}
        break;
      case 8: // terminal -> ENTITY_NAME, COLON, opt_linestart, REGEX
{ 
			SafeGrammarAction(() => { 
				ConstructedGrammar.DeclareTerminal(ValueStack[ValueStack.Depth-4].strVal, ValueStack[ValueStack.Depth-1].strVal, ValueStack[ValueStack.Depth-2].boolVal);
				ConstructedGrammar.AddLocation(ValueStack[ValueStack.Depth-4].strVal, LocationStack[LocationStack.Depth-4].Start);
			}, LocationStack[LocationStack.Depth-4].Start);
		}
        break;
      case 9: // opt_linestart -> LINESTART
{ CurrentSemanticValue.boolVal = true; }
        break;
      case 10: // opt_linestart -> /* empty */
{ CurrentSemanticValue.boolVal = false; }
        break;
      case 11: // pair -> ENTITY_NAME, COLON, LEFT, pair_border, RIGHT, pair_border
{
			SafeGrammarAction(() => { 
				ConstructedGrammar.DeclarePair(ValueStack[ValueStack.Depth-6].strVal, ValueStack[ValueStack.Depth-3].strSet, ValueStack[ValueStack.Depth-1].strSet);
				ConstructedGrammar.AddLocation(ValueStack[ValueStack.Depth-6].strVal, LocationStack[LocationStack.Depth-6].Start);
			}, LocationStack[LocationStack.Depth-6].Start);
		}
        break;
      case 12: // pair_border -> ID
{ CurrentSemanticValue.strSet = new HashSet<string>() { ValueStack[ValueStack.Depth-1].strVal }; }
        break;
      case 13: // pair_border -> REGEX
{ 	
			var generated = ConstructedGrammar.GenerateTerminal(ValueStack[ValueStack.Depth-1].strVal);
			ConstructedGrammar.AddLocation(generated, LocationStack[LocationStack.Depth-1].Start);
			CurrentSemanticValue.strSet = new HashSet<string>() { generated };
		}
        break;
      case 14: // pair_border -> LROUND_BRACKET, pair_border_group_content, RROUND_BRACKET
{ CurrentSemanticValue.strSet = ValueStack[ValueStack.Depth-2].strSet; }
        break;
      case 15: // pair_border_group_content -> pair_border
{ CurrentSemanticValue.strSet = ValueStack[ValueStack.Depth-1].strSet; }
        break;
      case 16: // pair_border_group_content -> pair_border_group_content, OR, pair_border
{ ValueStack[ValueStack.Depth-3].strSet.UnionWith(ValueStack[ValueStack.Depth-1].strSet); CurrentSemanticValue.strSet = ValueStack[ValueStack.Depth-3].strSet; }
        break;
      case 17: // nonterminal -> ENTITY_NAME, EQUALS, body
{ 
			var aliases = this.Aliases;
			this.Aliases = new HashSet<string>(); 
			
			SafeGrammarAction(() => { 
				ConstructedGrammar.DeclareNonterminal(ValueStack[ValueStack.Depth-3].strVal, ValueStack[ValueStack.Depth-1].altList);
				ConstructedGrammar.AddLocation(ValueStack[ValueStack.Depth-3].strVal, LocationStack[LocationStack.Depth-3].Start);
				
				if(aliases.Count > 0)
					ConstructedGrammar.AddAliases(ValueStack[ValueStack.Depth-3].strVal, aliases);
			}, LocationStack[LocationStack.Depth-3].Start);
		}
        break;
      case 18: // body -> body, OR, alternative, optional_alias
{ 
			CurrentSemanticValue.altList = ValueStack[ValueStack.Depth-4].altList; 
			ValueStack[ValueStack.Depth-2].altVal.Alias = ValueStack[ValueStack.Depth-1].strVal; 
			CurrentSemanticValue.altList.Add(ValueStack[ValueStack.Depth-2].altVal); 
		}
        break;
      case 19: // body -> alternative, optional_alias
{ 
			CurrentSemanticValue.altList = new List<Alternative>(); 
			ValueStack[ValueStack.Depth-2].altVal.Alias = ValueStack[ValueStack.Depth-1].strVal; 
			CurrentSemanticValue.altList.Add(ValueStack[ValueStack.Depth-2].altVal); 
		}
        break;
      case 20: // alternative -> alternative, entry
{ CurrentSemanticValue.altVal = ValueStack[ValueStack.Depth-2].altVal; CurrentSemanticValue.altVal.Add(ValueStack[ValueStack.Depth-1].entryVal); }
        break;
      case 21: // alternative -> /* empty */
{ CurrentSemanticValue.altVal = new Alternative(); }
        break;
      case 22: // optional_alias -> ARROW, ID
{ CurrentSemanticValue.strVal = ValueStack[ValueStack.Depth-1].strVal; this.Aliases.Add(ValueStack[ValueStack.Depth-1].strVal); }
        break;
      case 23: // optional_alias -> /* empty */
{ CurrentSemanticValue.strVal = null; }
        break;
      case 24: // entry -> context_option_groups, entry_core, entry_args, quantifier, 
               //          prec_nonempty
{ 		
			var opts = new SymbolOptionsManager();
			
			foreach(var group in ValueStack[ValueStack.Depth-5].optionGroupsDict)
			{
				foreach(var option in group.Value)
				{
					opts.Set(group.Key, option.Key, option.Value);
				}
			}
			
			if(ValueStack[ValueStack.Depth-2].optQuantVal.HasValue)
			{
				if(ValueStack[ValueStack.Depth-4].strVal.StartsWith(Grammar.ANY_TOKEN_NAME))
				{
					Log.Add(Message.Warning(
							"Использование квантификаторов с символом '" + Grammar.ANY_TOKEN_NAME + "' избыточно и не влияет на процесс разбора",
							LocationStack[LocationStack.Depth-5].Start,
							"LanD"
						));
				}
				else
				{			
					var generated = ConstructedGrammar.GenerateNonterminal(ValueStack[ValueStack.Depth-4].strVal, ValueStack[ValueStack.Depth-2].optQuantVal.Value, ValueStack[ValueStack.Depth-1].boolVal);
					ConstructedGrammar.AddLocation(generated, CurrentLocationSpan.Start);
					
					CurrentSemanticValue.entryVal = new Entry(generated, opts);
				}
			}
			
			if(CurrentSemanticValue.entryVal == null)
			{
				if(ValueStack[ValueStack.Depth-4].strVal.StartsWith(Grammar.ANY_TOKEN_NAME))
				{
					var args = new SymbolArguments();
					AnyArgument sugarOption;

					if(Enum.TryParse(ValueStack[ValueStack.Depth-4].strVal.Substring(Grammar.ANY_TOKEN_NAME.Length), out sugarOption))
						args.Set(sugarOption, ValueStack[ValueStack.Depth-3].dynamicList.Select(e=>(string)e)); 
					else
					{
						foreach(var opt in ValueStack[ValueStack.Depth-3].dynamicList)
						{
							var errorGroupName = String.Empty;
							
							if(opt is ArgumentGroup)
							{
								var group = (ArgumentGroup)opt;

								if(Enum.TryParse(group.Name, out sugarOption))
									args.Set(sugarOption, group.Arguments.Select(e=>(string)e)); 
								else
									errorGroupName = group.Name;
							}
							else if(opt is String)
							{
								if(Enum.TryParse((string)opt, out sugarOption))
									args.Set(sugarOption, new List<string>()); 
								else
									errorGroupName = (string)opt;
							}
							
							if(!String.IsNullOrEmpty(errorGroupName))
							{
								Log.Add(Message.Error(
									"При описании '" + Grammar.ANY_TOKEN_NAME + "' использовано неизвестное имя группы '" 
										+ errorGroupName + "', группа проигнорирована",
									LocationStack[LocationStack.Depth-5].Start,
									"LanD"
								));
							}
						}
					}				
					
					CurrentSemanticValue.entryVal = new Entry(Grammar.ANY_TOKEN_NAME, opts, args);
				}
				else
				{
					CurrentSemanticValue.entryVal = new Entry(ValueStack[ValueStack.Depth-4].strVal, opts);
				}
			}
		}
        break;
      case 25: // entry_args -> ARGS_LROUND_BRACKET, args, RROUND_BRACKET
{ CurrentSemanticValue.dynamicList = ValueStack[ValueStack.Depth-2].dynamicList; }
        break;
      case 26: // entry_args -> /* empty */
{ CurrentSemanticValue.dynamicList = new List<dynamic>(); }
        break;
      case 27: // context_option_groups -> context_option_groups, CATEGORY_NAME, 
               //                          ARGS_LROUND_BRACKET, context_options, RROUND_BRACKET
{ 
			CurrentSemanticValue.optionGroupsDict = ValueStack[ValueStack.Depth-5].optionGroupsDict; 
			CurrentSemanticValue.optionGroupsDict[ValueStack[ValueStack.Depth-4].strVal] = ValueStack[ValueStack.Depth-2].optionsDict;
		}
        break;
      case 28: // context_option_groups -> /* empty */
{ CurrentSemanticValue.optionGroupsDict = new Dictionary<string, Dictionary<string, List<dynamic>>>(); }
        break;
      case 29: // context_options -> context_options, COMMA, context_option
{
			CurrentSemanticValue.optionsDict = ValueStack[ValueStack.Depth-3].optionsDict;
			CurrentSemanticValue.optionsDict[ValueStack[ValueStack.Depth-1].optionTuple.Item1] = ValueStack[ValueStack.Depth-1].optionTuple.Item2;
		}
        break;
      case 30: // context_options -> context_option
{
			CurrentSemanticValue.optionsDict = new Dictionary<string, List<dynamic>>();
			CurrentSemanticValue.optionsDict[ValueStack[ValueStack.Depth-1].optionTuple.Item1] = ValueStack[ValueStack.Depth-1].optionTuple.Item2;
		}
        break;
      case 31: // context_option -> ID, context_opt_args
{ CurrentSemanticValue.optionTuple = new Tuple<string, List<dynamic>>(ValueStack[ValueStack.Depth-2].strVal, ValueStack[ValueStack.Depth-1].dynamicList); }
        break;
      case 32: // context_opt_args -> ARGS_LROUND_BRACKET, args, RROUND_BRACKET
{ CurrentSemanticValue.dynamicList = ValueStack[ValueStack.Depth-2].dynamicList; }
        break;
      case 33: // context_opt_args -> /* empty */
{ CurrentSemanticValue.dynamicList = new List<dynamic>(); }
        break;
      case 34: // prec_nonempty -> PREC_NONEMPTY
{ CurrentSemanticValue.boolVal = true; }
        break;
      case 35: // prec_nonempty -> /* empty */
{ CurrentSemanticValue.boolVal = false; }
        break;
      case 36: // quantifier -> OPTIONAL
{ CurrentSemanticValue.optQuantVal = ValueStack[ValueStack.Depth-1].quantVal; }
        break;
      case 37: // quantifier -> ZERO_OR_MORE
{ CurrentSemanticValue.optQuantVal = ValueStack[ValueStack.Depth-1].quantVal; }
        break;
      case 38: // quantifier -> ONE_OR_MORE
{ CurrentSemanticValue.optQuantVal = ValueStack[ValueStack.Depth-1].quantVal; }
        break;
      case 39: // quantifier -> /* empty */
{ CurrentSemanticValue.optQuantVal = null; }
        break;
      case 40: // entry_core -> REGEX
{ 
			CurrentSemanticValue.strVal = ConstructedGrammar.GenerateTerminal(ValueStack[ValueStack.Depth-1].strVal);
			ConstructedGrammar.AddLocation(CurrentSemanticValue.strVal, CurrentLocationSpan.Start);
		}
        break;
      case 41: // entry_core -> ID
{ CurrentSemanticValue.strVal = ValueStack[ValueStack.Depth-1].strVal; }
        break;
      case 42: // entry_core -> group
{ CurrentSemanticValue.strVal = ValueStack[ValueStack.Depth-1].strVal; }
        break;
      case 43: // group -> LROUND_BRACKET, body, RROUND_BRACKET
{ 
			CurrentSemanticValue.strVal = ConstructedGrammar.GenerateNonterminal(ValueStack[ValueStack.Depth-2].altList);
			ConstructedGrammar.AddLocation(CurrentSemanticValue.strVal, CurrentLocationSpan.Start);
		}
        break;
      case 46: // category_block -> CATEGORY_NAME, option_or_block
{
			foreach(var option in ValueStack[ValueStack.Depth-1].optionsList)
			{
				SafeGrammarAction(() => {
					ConstructedGrammar.SetOption(ValueStack[ValueStack.Depth-2].strVal, option.Name, option.Symbols, option.Arguments);
				}, LocationStack[LocationStack.Depth-2].Start);
			}
		}
        break;
      case 47: // option_or_block -> option
{ CurrentSemanticValue.optionsList = new List<OptionDeclaration>(){ ValueStack[ValueStack.Depth-1].optDeclVal }; }
        break;
      case 48: // option_or_block -> LCURVE_BRACKET, options, RCURVE_BRACKET
{ CurrentSemanticValue.optionsList = ValueStack[ValueStack.Depth-2].optionsList; }
        break;
      case 49: // options -> /* empty */
{ CurrentSemanticValue.optionsList = new List<OptionDeclaration>(); }
        break;
      case 50: // options -> options, option
{ CurrentSemanticValue.optionsList = ValueStack[ValueStack.Depth-2].optionsList; ValueStack[ValueStack.Depth-2].optionsList.Add(ValueStack[ValueStack.Depth-1].optDeclVal);  }
        break;
      case 51: // option -> OPTION_NAME, opt_args, grammar_entities_list
{
			CurrentSemanticValue.optDeclVal = new OptionDeclaration()
			{
				Name = ValueStack[ValueStack.Depth-3].strVal,
				Arguments = ValueStack[ValueStack.Depth-2].dynamicList,
				Symbols = ValueStack[ValueStack.Depth-1].strList
			};
		}
        break;
      case 52: // opt_args -> LROUND_BRACKET, args, RROUND_BRACKET
{ CurrentSemanticValue.dynamicList = ValueStack[ValueStack.Depth-2].dynamicList; }
        break;
      case 53: // opt_args -> /* empty */
{ CurrentSemanticValue.dynamicList = new List<dynamic>(); }
        break;
      case 54: // args -> args, COMMA, argument
{ 
			CurrentSemanticValue.dynamicList = ValueStack[ValueStack.Depth-3].dynamicList; 
			CurrentSemanticValue.dynamicList.Add(ValueStack[ValueStack.Depth-1].dynamicVal); 
		}
        break;
      case 55: // args -> argument
{ CurrentSemanticValue.dynamicList = new List<dynamic>(){ ValueStack[ValueStack.Depth-1].dynamicVal }; }
        break;
      case 56: // argument -> RNUM
{ CurrentSemanticValue.dynamicVal = ValueStack[ValueStack.Depth-1].doubleVal; }
        break;
      case 57: // argument -> REGEX
{
			var generated = ConstructedGrammar.GenerateTerminal((string)ValueStack[ValueStack.Depth-1].strVal);
			ConstructedGrammar.AddLocation(generated, LocationStack[LocationStack.Depth-1].Start);		
			CurrentSemanticValue.dynamicVal = generated;
		}
        break;
      case 58: // argument -> STRING
{ CurrentSemanticValue.dynamicVal = ValueStack[ValueStack.Depth-1].strVal.Substring(1, ValueStack[ValueStack.Depth-1].strVal.Length - 2); }
        break;
      case 59: // argument -> ID
{ CurrentSemanticValue.dynamicVal = ValueStack[ValueStack.Depth-1].strVal; }
        break;
      case 60: // argument -> argument_group
{ CurrentSemanticValue.dynamicVal = ValueStack[ValueStack.Depth-1].argGroupVal; }
        break;
      case 61: // argument_group -> ID, ARGS_LROUND_BRACKET, args, RROUND_BRACKET
{ 
			CurrentSemanticValue.argGroupVal = new ArgumentGroup()
			{
				Name = ValueStack[ValueStack.Depth-4].strVal,
				Arguments = ValueStack[ValueStack.Depth-2].dynamicList
			};
		}
        break;
      case 62: // grammar_entities_list -> grammar_entities_list, grammar_entity
{ 
			CurrentSemanticValue.strList = ValueStack[ValueStack.Depth-2].strList;	
			if(!String.IsNullOrEmpty(ValueStack[ValueStack.Depth-1].strVal))
				CurrentSemanticValue.strList.Add(ValueStack[ValueStack.Depth-1].strVal);
		}
        break;
      case 63: // grammar_entities_list -> /* empty */
{ CurrentSemanticValue.strList = new List<string>(); }
        break;
      case 64: // grammar_entity -> ID
{ CurrentSemanticValue.strVal = ValueStack[ValueStack.Depth-1].strVal; }
        break;
      case 65: // grammar_entity -> REGEX
{ 
			CurrentSemanticValue.strVal = ConstructedGrammar.GetTerminal(ValueStack[ValueStack.Depth-1].strVal);
			
			if(String.IsNullOrEmpty(CurrentSemanticValue.strVal))
			{
				Log.Add(Message.Error(
					"Не найден токен, определяемый регулярным выражением " + ValueStack[ValueStack.Depth-1].strVal,
					LocationStack[LocationStack.Depth-1].Start,
					"LanD"
				));
			}
		}
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


private void SafeGrammarAction(Action action, PointLocation loc)
{
	try
	{
		action();
	}
	catch(IncorrectGrammarException ex)
	{
		Log.Add(Message.Error(
			ex.Message,
			loc,
			"LanD"
		));
	}
}
}
}
